_BASE_: "Base-TridentNet-Fast-C4.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_101_C4_3x/138204752/model_final_298dad.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101